# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

env = GDK_SCALE,2

# Laptop screen - main display
monitor = eDP-1, 1920x1080@144, 0x0, 1.5

# External MSI monitor - same scale as laptop
monitor = HDMI-A-1, 1920x1080@60, 1280x0, 1.5
